---
# Database password secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-db-secret
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.worker.database.password | b64enc | quote }}

---
{{- if and (not .Values.redis.enabled) .Values.externalRedis.password }}
# External Redis password secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-redis-secret
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}

---
{{- if and .Values.worker.aws.accessKeyId .Values.worker.aws.secretAccessKey }}
# AWS credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-aws-secret
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
type: Opaque
data:
  accessKeyId: {{ .Values.worker.aws.accessKeyId | b64enc | quote }}
  secretAccessKey: {{ .Values.worker.aws.secretAccessKey | b64enc | quote }}
{{- end }}